<?php

error_reporting(E_ALL ^ ~E_DEPRECATED);

require_once __DIR__ . "/vendor/autoload.php";

use mikehaertl\wkhtmlto\Pdf;

$html = $_POST['widgetcode'];
$name = $_POST['name'];
$info = $_POST['info'];

$img = '';
if ($_FILES['logo']['tmp_name']) {

    $type     = $_FILES['logo']['type'];
    $filename = $_FILES['logo']['tmp_name'];

    // Read image path, convert to base64 encoding
    $imageData = base64_encode(file_get_contents($filename));

    // Format the image SRC:  data:{mime};base64,{data};
    // $src = 'data:'.mime_content_type($image).';base64,'.$imageData;
    $src = 'data:' . $type . ';base64,' . $imageData;

    $img = '<img style="max-width:100%; max-height:400px;" src="' . $src . '"/>';

}

$dom                     = new DOMDocument();
//$dom->encoding = 'utf-8';
$dom->preserveWhiteSpace = false;
@$dom->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));
$xpath = new DomXPath($dom);

// remove item name
// foreach ($xpath->query("//a/text()") as $item) {
//     $item->parentNode->removeChild($item);
// }

// remove item price
// foreach ($xpath->query("//a/span") as $item) {
//     $item->parentNode->removeChild($item);
// }

// remove add by sudsol
foreach ($xpath->query('//a[@href="http://www.sudsol.org/"]') as $item) {
    $item->parentNode->removeChild($item);
}
//echo $oDom->saveHTML();
$html = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';
$html .= $dom->saveHTML();
// $html = str_replace('120px', '170px', $html);


// $pdf = new Pdf;
// $options = array("binary" => "/usr/local/bin/wkhtmltopdf.sh");
$options = array("binary" => "/home/sudsol5/public_html/wkhtmltox/bin/wkhtmltopdf");
$pdf     = new Pdf($options);

$trial = '<a style="font-size:10px;" href="http://www.sudsol.org/" rel="nofollow" target="_blank">Generated by SUDSOL, Free Trial at www.sudsol.org</a>';

$pdf->addPage("<html><h1>$name</h1>$info<br><br>$img<br><br>$html<br><br>$trial</html>");

// header('Access-Control-Allow-Origin: *');
// $rnd=rand(100000,999999);
// $file="/pdf/sudsol.$rnd.pdf";
if (!$pdf->send('sudsol.pdf')) {
// if (!$file = $pdf->toString()) {
    // if (!$pdf->saveAs(__DIR__ . $file)) {
    echo $pdf->getError();
}

